### ISSUE TITLE
Board routing

### ISSUE THREAD

**Issue by anidea** [adafruit/Adafruit-Ethernet-FeatherWing-PCB#1]
The quality of routing on this board is low.  It should be used to copy from.  The decoupling alone is poor.  I'm honestly amazed it works.  Analog 3.3V shown.

![image](https://user-images.githubusercontent.com/4162332/28652654-10abe5ba-7257-11e7-8941-33cc242c9032.png)

**Comment by ladyada** [comment]
submit a commit with better routing and we will check it out, thx!

**Comment by anidea** [comment]
I have it in Altium.  Would that be worth sharing?  I mostly wanted to point it out so that someone else using this design would be aware.

**Comment by ladyada** [comment]
hiya, please update the original eagle file, that way we can update it with your awesome routing!
